---
title: "Untitled"
author: "Jaehwan Lim"
date: "January 12, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(haven)
theme_set(theme_light())

gwf <- read_excel("gwf-data/GWF Autocratic Regimes.xlsx")
gwf_all <- read_dta("gwf-data/GWF_AllPoliticalRegimes.dta")
gwf_tscs <- read_dta("gwf-data/GWFtscs.dta")

gwf_all_autocracy <- gwf_all %>% 
  filter(gwf_nonautocracy != "democracy")
```

## What type of authoritarian regime is most common today?

```{r message=FALSE, warning=FALSE}
library(lubridate)

gwf_all %>% 
  filter(gwf_nonautocracy != "democracy") %>%
  filter(gwf_regimetype != "NA") %>% 
  mutate(gwf_regimetype = fct_recode(gwf_regimetype, military = "indirect military", 
                                   military = "military-personal", 
                                   party = "party-military", 
                                   party = "party-military-personal", 
                                   party = "party-personal", 
                                   party = "oligarchy")) %>% 
  group_by(year) %>%
  count(gwf_regimetype) %>% 
  ggplot(aes(year, n)) +
  geom_line(aes(color = gwf_regimetype)) + 
  scale_x_continuous(breaks = c(1950, 1960, 1970, 1980, 1990, 2000)) +
  labs(title = "Number of authoritarian regimes in power by type, 1946-2010", 
       x = "Year", 
       y = "Frequency") 
  
```

## Are Today's authoritarian regimes more durable than those of the past?

```{r}
gwf_all_autocracy %>% 
  group_by(year) %>% 
  summarize(median_years = median(gwf_duration)) %>% 
  ggplot(aes(year, median_years)) +
  geom_line() +
  expand_limits(y = 0) + 
  scale_x_continuous(limits = c(1951, 2010))
  
```

## How authoritarian regimes fall?

```{r message=FALSE, warning=FALSE}
gwf_post <- gwf %>% 
  mutate(gwf_howend2 = recode(gwf_howend, `0` = "NA", 
                              `1` = "Rule change", 
                              `2` = "Election", 
                              `3` = "Election", 
                              `4` = "Uprising", 
                              `5` = "Coup", 
                              `6` = "Insurgency", 
                              `7` = "Foreign", 
                              `8` = "NA",
                              `9` = "End of state")) %>%
  filter(gwf_howend2 != "NA") %>% 
  filter(gwf_endyr >= 1990) %>% 
  count(gwf_howend2) %>% 
  mutate(prop = n / sum(n)) %>% 
  mutate(gwf_howend2 = fct_reorder(gwf_howend2, prop))

gwf %>% 
  mutate(gwf_howend2 = recode(gwf_howend, `0` = "NA", 
                              `1` = "Rule change", 
                              `2` = "Election", 
                              `3` = "Election", 
                              `4` = "Uprising", 
                              `5` = "Coup", 
                              `6` = "Insurgency", 
                              `7` = "Foreign", 
                              `8` = "NA",
                              `9` = "End of state")) %>%
  filter(gwf_howend2 != "NA") %>%
  count(gwf_howend2) %>% 
  mutate(prop = n / sum(n)) %>% 
  left_join(gwf_post, by = "gwf_howend2") %>% 
  gather(prop, frequency, prop.x, prop.y) %>% 
  mutate(gwf_howend2 = fct_relevel(gwf_howend2, "Coup", "Election", "Uprising", "Insurgency", "Rule change", "Foreign", "End of state")) %>% 
  ggplot(aes(gwf_howend2, frequency, fill = prop)) +
  geom_col(position = "dodge") + 
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "How authoritarian regimes fell", 
       x = "Failure type", 
       y = "Percent") + 
  scale_fill_discrete(name = "", 
                      breaks = c("prop.x", "prop.y"), 
                      labels = c("1946-2010", "Post-Cold war")) 

```

```{r}
gwf_all_autocracy %>% 
  filter(gwf_regimetype != "NA") %>% 
  mutate(gwf_regimetype = fct_recode(gwf_regimetype, military = "indirect military", 
                                   military = "military-personal", 
                                   party = "party-military", 
                                   party = "party-military-personal", 
                                   party = "party-personal", 
                                   party = "oligarchy")) %>%
  count(gwf_country, gwf_regimetype, gwf_spell) %>% 
  group_by(gwf_regimetype) %>% 
  summarize(years = sum(n))

```

# Which regime comes after regime collapse?
```{r}
gwf_tscs %>% 
  filter(gwf_fail == 1) %>% 
  filter(gwf_regimetype != "NA", 
         gwf_regimetype != "monarchy") %>% 
  mutate(gwf_regimetype = fct_recode(gwf_regimetype, military = "indirect military", 
                                   military = "military-personal", 
                                   party = "party-military", 
                                   party = "party-based",
                                   party = "party-personal-military", 
                                   party = "party-personal", 
                                   party = "oligarchy")) %>% 
  mutate(gwf_fail_subsregime = factor(gwf_fail_subsregime, 
                                      1:3, 
                                      labels = c("democrary", "autocratic", "others"))) %>% 
  count(gwf_regimetype, gwf_fail_subsregime, sort = T) %>%
  group_by(gwf_regimetype) %>% 
  mutate(pct_n = n / sum(n)) %>% 
  ungroup() %>% 
  mutate(gwf_regimetype = fct_recode(gwf_regimetype, 
                                     "military (n=76)" = "military", 
                                     "party (n=58)" = "party", 
                                     "personal (n=77)" = "personal")) %>% 
  ggplot(aes(gwf_regimetype, pct_n)) +
  geom_col(aes(fill = gwf_fail_subsregime)) +
  scale_y_continuous(labels = scales::percent) +
  theme(legend.title = element_blank(), 
        legend.position = "bottom") +
  labs(title = "Regime type after autocratic collapse", 
       subtitle = "Democracy is most likely for military regimes",
       x = " ",
       y = "Percent", 
       caption = "Source: GWF(2014)")
```

