---
title: "Untitled"
author: "Jaehwan Lim"
date: "February 1, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(haven)

gwf_raw <- read_dta("GWF.dta")

theme_set(theme_light())
```

## plotting China's factor score by year

```{r}
library(psych)

gwf_china_processed <- gwf_china %>% 
  select(-cowcode, -region, -foreignimposd, -ldr1styear, -starts_with("gwf_"), -starts_with("period"), seizure_foreign, sectyapp_mil, paramil_noparamil) %>% 
  select(-ld, -coldwar, -country, -casename, -G_age, -post_exit_type, -post_exit_fate, -partyexcom_noexcom, -legnoms_priordict, -legnoms_noleg, -legnoms_nooppose, -electldr_family, -year)

gwf_china_pcm <- prcomp(gwf_china_processed, center = T, scale. = T)

factanal(x = gwf_china_processed, factors = 3)

gwf_china_processed <- gwf_china %>% 
  select(-cowcode, -region, -foreignimposd, -ldr1styear, -starts_with("gwf_"), -starts_with("period"), seizure_foreign, sectyapp_mil, paramil_noparamil) %>% 
  select(-ld, -coldwar, -country, -casename, -G_age, -post_exit_type, -post_exit_fate, -partyexcom_noexcom, -legnoms_priordict, -legnoms_noleg, -legnoms_nooppose, -electldr_family, -year)


```

```{r}
library(ggbiplot)
library(broom)

gwf_per <- gwf_raw %>% 
  select(sectyapp_pers, officepers, heirfamily, paramil_pers, leaderrelatvs, milmerit_pers, milnotrial, partyexcom_pers, heirclan, partyrbrstmp) 

gwf_per_factanal <- factanal(gwf_per, factors = 1)
gwf_per_pca <- prcomp(gwf_per, center = T, scale. = T)

gwf_per_factanal$loadings


```
```{r}

gwf_processed <- gwf_raw %>% 
  select(-cowcode, -region, -foreignimposd, -ldr1styear, -starts_with("gwf_"), -starts_with("period"), seizure_foreign, sectyapp_mil, paramil_noparamil, -seizure_foreign, -partyhistory_postseizure, -partymilit2) %>% 
  select(-ld, -coldwar, -country, -casename, -G_age, -post_exit_type, -post_exit_fate, -partyexcom_noexcom, -legnoms_priordict, -legnoms_noleg, -legnoms_nooppose, -electldr_family, -year)

gwf_fa <- fa(gwf_processed, nfactors = 3)
gwf_fa$loadings
gwf_fa$scores

fa_scores_tibble <- as_tibble(gwf_fa$scores)
gwf_raw_scores <- cbind(gwf_raw, fa_scores_tibble)

gwf_raw_scores %>% 
  filter(gwf_country == "China") %>% 
  select(year, "party strength" = MR1, "military autonomy" = MR2, personalism = MR3) %>%
  gather(score, value, -year) %>% 
  mutate(score = fct_reorder(score, value)) %>% 
  ggplot(aes(year, value, linetype = score)) + 
  geom_line() + 
  scale_x_continuous(breaks = seq(1950, 2010, 10)) +
  labs(title = "Figure 1. Three dimensions of dictatorship, China 1949-2010", 
       x = "Year", 
       y = "Latent dimensions", 
       caption = "Data from Geddes, Wright, and Frantz 2014") +
  theme(legend.position="bottom") +
  theme(legend.title=element_blank())

```

```{r}
gwf_scores_tidied <- gwf_raw_scores %>% select(year, "country" = gwf_country, "party_strength" = MR1, "military_autonomy" = MR2, personalism = MR3) 

gwf_scores_tidied %>% filter(country == c("China", "Korea North", "Vietnam", "Soviet Union", "Indonesia")) %>% 
  mutate(country = recode(country, "Korea North" = "North Korea")) %>% 
  ggplot(aes(year, personalism, col = country)) + 
  geom_line() +
  scale_x_continuous(breaks = seq(1950, 2010, 10)) +
  labs(title = "Figure 2. Dimension of personalism: China, Vietnam, North Korea, 1949-2010", 
       x = "Year", 
       y = "Personalism index", 
       caption = "Data from Geddes, Wright, and Frantz 2014") +
  theme(legend.position="bottom") +
  theme(legend.title=element_blank())
  

```

